# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPCznOSwczgNkcH8ZytZRXiNwWj5UuIk

###Decision Tree Regressor
"""

# Initialize Decision Tree Regressor
dt_model = DecisionTreeRegressor(random_state=74)

# Fit the model
dt_model.fit(X_train_scaled, y_train)

# Predict on test set
y_pred_dt = dt_model.predict(X_test_scaled)

# Evaluate the model
mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = mean_squared_error(y_test, y_pred_dt, squared=False)  # Calculate RMSE
mae_dt = mean_absolute_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print("Decision Tree Model Metrics:")
print("Mean Squared Error:", mse_dt)
print("Root Mean Squared Error:", rmse_dt)
print("Mean Absolute Error:", mae_dt)
print("R-squared Score:", r2_dt)
